# Generated by Django 5.2 on 2025-05-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Calzado', 'Calzado'), ('Accesorios', 'Accesorios'), ('Equipamiento', 'Equipamiento'), ('Tecnología', 'Tecnología'), ('Nutrición', 'Nutrición')], max_length=200, null=True),
        ),
    ]
