# Generated by Django 5.2 on 2025-05-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
